import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={process.env.FAVICON} sizes="any" />
      </head>
      <body className={inter.className}>
        <div className="wraper">
          <Header />

          <section>{children}</section>

          <Footer />
        </div>
      </body>
    </html>
  );
}
